title: Relaycorp
description: Tackling humanity's toughest and most overlooked communication challenges
logo: /assets/logo.png

markdown: kramdown
theme: jekyll-theme-minimal

github:
  is_project_page: false
